services:
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile.php.dev
    restart: always
    volumes:
      - /opt/services/services/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mapdata-network

networks:
  mapdata-network:
    external: true
