services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - /opt/services/services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - /opt/services/services/nginx/conf.d:/etc/nginx/conf.d:ro
      # - /opt/services/services/nginx/default:/etc/nginx/default:ro
      # - nginx_data:/etc/nginx/conf.d:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mapdata-network
      - default

# volumes:
#   nginx_data:
#     driver: local

networks:
  default:
    driver: bridge
  mapdata-network:
    external: true
